USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=delete_inactive_users
PACKAGE_VERSION=1.0
REVERSE_DOMAIN=org.dankeller
PAYLOAD=\
	pack-usr-local-sbin-delete_inactive_users.sh \
	pack-Library-LaunchDaemons-org.dankeller.deleteInactiveUsers.plist