USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=freeze_homedirs
PACKAGE_VERSION=1.0
REVERSE_DOMAIN=org.dankeller
PAYLOAD=\
	pack-usr-local-sbin-freeze_homedirs.sh \
	pack-Library-LaunchDaemons-org.dankeller.freezeHomedirs.plist